apiVersion: v1
kind: Service
metadata:
  name: openai-chat-service
  namespace: default
spec:
  selector:
    app: openai-chat-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  type: LoadBalancer