apiVersion: v1
kind: Service
metadata:
  name: chatbot-easy-rag
  namespace: default
spec:
  selector:
    app: chatbot-easy-rag
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  type: LoadBalancer
  sessionAffinity: ClientIP