apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-sa-credentials
  namespace: default
spec:
  refreshInterval: 1h               # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager-store  # name of the SecretStore (or kind specified)
    namespace: external-secrets
  target:
    name: gcp-sa-credentials        # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: external-secrets-sa.json
    remoteRef:
      key: external-secrets-sa     # name of the GCPSM secret key
