apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: cloud-native-experience-lab
      auth:
        workloadIdentity:
          clusterLocation: europe-west4
          clusterName: k8s-native-java-ai
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          # clusterProjectID: cloud-native-experience-lab
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets