apiVersion: v1
kind: Service
metadata:
  name: ollama-chat-service
  namespace: default
spec:
  selector:
    app: ollama-chat-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  type: LoadBalancer