apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-proxy-deployment
  namespace: default
  labels:
    app: openai-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openai-proxy
  template:
    metadata:
      labels:
        app: openai-proxy
    spec:
      containers:
      - name: openai-proxy
        image: ghcr.io/lreimer/k8s-native-java-ai-openai-proxy:main
        ports:
        - name: http
          containerPort: 10000
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "500m"
