apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/services
  prune: true
  dependsOn:
    - name: platform
  sourceRef:
    kind: GitRepository
    name: flux-system