apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: "3.3.3"
  interval: 1h0m0s
  releaseName: kyverno
  targetNamespace: kyverno
  values:
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 3
    cleanupController:
      replicas: 3
    reportsController:
      replicas: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: "3.3.1"
  interval: 1h0m0s
  releaseName: kyverno-policies
  targetNamespace: kyverno