apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: langflow-ide
  namespace: flux-system
spec:
  chart:
    spec:
      chart: langflow-ide
      sourceRef:
        kind: HelmRepository
        name: langflow
      version: "0.1.0"
  interval: 1h0m0s
  releaseName: langflow-ide
  targetNamespace: langflow
  values: 
    langflow:
      backend:
        env:
          - name: "LANGFLOW_PORT"
            value: "7860"
        sqlite:
          enabled: true
          volume:
            size: "1Gi"
            existingStorageClassName: {}
            # For GCP
            storageClass:
              provisioner: kubernetes.io/gce-pd
              type: pd-ssd
              fsType: ext4
              extraParams:
                replication-type: none

# ---
#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: langflow-runtime
#  namespace: flux-system
#spec:
#  chart:
#    spec:
#      chart: langflow-runtime
#      sourceRef:
#        kind: HelmRepository
#        name: langflow
#      version: "0.1.0"
#  interval: 1h0m0s
#  releaseName: langflow-runtime
#  targetNamespace: langflow